people = {
    "Brogi, Giacomo": "2213",
    "Alinari, Fratelli": "1532",
    "Anderson, James": "1192",
    "Perotti, Mario": "184",
    "Vasari, Cesare": "171",
    "Fiorentini, Pietro": "140",
    "Sansoni, Mario": "131",
    "Liverani, Giorgio": "125",
    "Boccardi, Cosimo": "123",
    "Hobbs, Sherley": "111",
    "Savio, Oscar": "107",
    "Keyes, Murray Kendall": "105",
    "Bulloz, Jacques-Ernest": "95",
    "Bassani, Gigi": "84",
    "Moscioni, Romualdo": "75",
    "Rigamonti, F.": "73",
    "Cipriani, Nicol\u00ef\u00bf\u00bd": "72",
    "Naya, Carlo": "68",
    "Rampazzi, Giustino": "67",
    "Schiff, John D.": "67",
    "Quaresima, Mario": "63",
    "Marcozzi, Carlo": "61",
    "Carletti, Angelo": "60",
    "Vaghi, Luigi": "57",
    "Croci, Felice": "54",
    "Lombardi, Paolo": "51",
    "Brogiolo, Mario": "46",
    "Salviati, Paolo": "42",
    "Zani, Dino": "41",
    "Rossi, Paolo": "40",
    "Grassi, Cesare": "36",
    "Mari, Gianni": "35",
    "Newbery, Sydney W.": "35",
    "Fedeli, Marcello": "32",
    "Freeman, John R. and Co.": "27",
    "Swoger, Arthur": "26",
    "Todini, Filippo": "25",
    "Guerra, Antonio": "22",
    "Sansaini, Salvatore": "21",
    "Guidotti, Bartolomeo": "20",
    "Chauffourier, Gustave Eug\u00ef\u00bf\u00bdne": "18",
    "Lunghi, Amerigo": "18",
    "Perez, Ferdinando": "18",
    "Taramelli, Andrea": "18",
    "Savastano, Frank S.": "17",
    "Dubray, Luigi": "16",
    "Verri, Candido": "16",
    "Bowron, Scott": "15",
    "Fyman, Vladim\u00ef\u00bf\u00bdr": "15",
    "Gray, William Edward": "15",
    "Martin, Alfred R.": "15",
    "Reale, Ettore": "15",
    "Tacchini, Giuseppe": "15",
    "Visentini, Guglielmo": "15",
    "Bacci, Attilio": "13",
    "Juley, Peter A. and Son": "13",
    "Brammer, H.": "12",
    "Pettinger, K.": "12",
    "Conger, M. N.": "11",
    "Mansell, W. F.": "11",
    "Baldassari, Marco": "10",
    "Bombelli, Girolamo": "10",
    "Manzotti, Fratelli": "10",
    "Puterbaugh, Rollyn": "10",
    "Steinkopf, Walter": "10",
    "Como, Michele": "9",
    "Gamberoni, Silvio": "9",
    "Guazzi, Carlo": "9",
    "Mignini, Ettore": "9",
    "Rossi, Zoe": "9",
    "Sereni, Michele Alberto": "9",
    "Benedik, Valentin": "8",
    "Filippi, Tomaso": "8",
    "Gray, R.": "8",
    "Jones, Bruce C.": "8",
    "Poliak, I.": "8",
    "Arceci, Mauro": "7",
    "Feist, Thomas": "7",
    "Marr, Thomas E.": "7",
    "Marzullo, Gerardo": "7",
    "Pegorini, Oscar": "7",
    "Saviantonio, Vinicio": "7",
    "Vermard, Georges": "7",
    "Alivernini, Eraldo": "6",
    "Barsotti, Ferdinando": "6",
    "Benvenuti, Cesare": "6",
    "Ehm, Josef": "6",
    "Engman, Anders": "6",
    "Mazzanti, Paolo": "6",
    "Weston, Sam": "6",
    "Benedetti, Silvestro": "5",
    "Blomstrann, E. Irving": "5",
    "Bucci, R.": "5",
    "Camponogara, J.": "5",
    "Cushing, George M.": "5",
    "Guido, Giovanni": "5",
    "Heaton, Wallace": "5",
    "Offner, Mortimer": "5",
    "Ottavianelli, Franco": "5",
    "Piccardy, Charles": "5",
    "Pollitzer, Eric": "5",
    "Raffaelli, Luigi": "5",
    "Shepard, Myron S.": "5",
    "Vannini, Carlo": "5",
    "Anders, J\u00ef\u00bf\u00bdrg P.": "4",
    "Brusa, Giovanni Battista": "4",
    "Carboni, C.": "4",
    "Como, Giorgio": "4",
    "Fiorucci, Carlo": "4",
    "Franzosi, Tita": "4",
    "Hymers, Robert Patterson": "4",
    "Malenotti, Gino": "4",
    "Obert, Karl": "4",
    "Oto, Maximilian": "4",
    "Quiresi, Ezio": "4",
    "Scherb, Julius": "4",
    "Schmidt, Otto": "4",
    "Sciamanna, Umberto": "4",
    "Scott, Tom": "4",
    "Sunami, Soichi": "4",
    "Tomba, Umberto": "4",
    "Zangheri, Giampiero": "4",
    "Baker, Oliver": "3",
    "Balogh, Rudolf": "3",
    "Barzacchi, Cesare": "3",
    "Brenwasser, Donald": "3",
    "Castagneri, Mario": "3",
    "Ceccato, A.": "3",
    "Ciacchi, Leonello": "3",
    "Cordes, Paul": "3",
    "Corradini, L.": "3",
    "Dingjan, A.": "3",
    "Fabbri, Teodoro": "3",
    "Fini, Giuseppe": "3",
    "Gatti, Dario": "3",
    "Geoghegan, Thomas F.": "3",
    "Laib, Paul": "3",
    "Lotti, Carlo": "3",
    "Malter, Barbara": "3",
    "Mannelli, Anchise": "3",
    "Moretti, Mario": "3",
    "Pezzetta, Silvano": "3",
    "Rampazzi, Ferruccio": "3",
    "Sansaini, Renato": "3",
    "Sommer, Giorgio": "3",
    "Tosi, Libero": "3",
    "Underwood, John": "3",
    "Zagnoli, Alfonso": "3",
    "Agosto, Mario": "2",
    "Anelli, Sergio": "2",
    "Bazzechi, Ivo": "2",
    "Beccaria, P.": "2",
    "Bestetti, C.": "2",
    "Beyer, G\u00ef\u00bf\u00bdnther": "2",
    "Borel, L.": "2",
    "Bottura, Erminio": "2",
    "Bozzetto, Mario": "2",
    "Brembilla, Efrem": "2",
    "Brizi, Fulvio": "2",
    "Brunetti, Federico": "2",
    "Burnell, William Earl": "2",
    "Calderisi, Michele Valentino": "2",
    "Cascianelli, P.": "2",
    "Chiolini, Guglielmo": "2",
    "Cipollina, Paolo": "2",
    "Conner, Con": "2",
    "Cortopassi, Ettore": "2",
    "Danesin, Menotti": "2",
    "Edelmann, Ursula": "2",
    "Eilers, Bernard F.": "2",
    "Elsam, Mann and Cooper": "2",
    "Emmer, Claudio": "2",
    "Giraldi, Stefano": "2",
    "Hartmann, W.": "2",
    "Hollow, Matthew": "2",
    "Janisson, J.": "2",
    "Jurysek, Jaroslav": "2",
    "Knoerr, B. K.": "2",
    "Lensini, Fabio": "2",
    "Lomeo, Angelo": "2",
    "Manuli, Ugo": "2",
    "Manusardi, B.P.": "2",
    "Maraglio, E.": "2",
    "Marini, Sisinio": "2",
    "Matarazzo, Giovanni": "2",
    "Mattei, Franco": "2",
    "Mazzia, F.": "2",
    "Monti, Paolo": "2",
    "Neubert, Ladislav": "2",
    "Peyrot, G.": "2",
    "Regales, Ernesto": "2",
    "Rossetti, Secondo": "2",
    "Russell, Walter J.": "2",
    "Sauter, George Philip": "2",
    "Scansani, Walter": "2",
    "Sinigaglia, Gian": "2",
    "Sommariva, Emilio": "2",
    "Sorgato, Ferruccio": "2",
    "Sproul, A. E.": "2",
    "Steinmetz, Joseph Janney": "2",
    "Sterle, Giacomo (Studio Ceregato)": "2",
    "Sylvestre, Jules": "2",
    "Uht, Charles": "2",
    "Vicari, Vincenzo": "2",
    "Vose, Herbert P.": "2",
    "Walker, Emery": "2",
    "Wyatt, A. J.": "2",
    "Zimmermann, G\u00ef\u00bf\u00bdrard": "2",
    "Alari, Massimo": "1",
    "Allemand, Auguste": "1",
    "Ancillotti, Carlo": "1",
    "Angerer, Victor": "1",
    "Aragozzini, Vincenzo": "1",
    "Arlaud, Jean": "1",
    "Artigue, L.": "1",
    "Aucone, Giovanni": "1",
    "Ballerini, E.": "1",
    "Balzarini, C.": "1",
    "Baraldi, Fratelli": "1",
    "Bauer, Robert A.E.": "1",
    "Berardi, Mario": "1",
    "Bertani, Ettore": "1",
    "Bianchetti, Gian Franco": "1",
    "Bijtebier, Paul": "1",
    "Bolletti, Francesco": "1",
    "Bosch, A.": "1",
    "Bovolenta, Alfio": "1",
    "Bravo, Dante": "1",
    "Brenwasser, Eugene": "1",
    "Brisighelli, Attilio": "1",
    "Burstein, Barney": "1",
    "Cacco, Giorgio": "1",
    "Camera, Giuseppe": "1",
    "Candio, Italo": "1",
    "Cappellani, Dante": "1",
    "Cargnel, Bruno": "1",
    "Carlebach, Alfred": "1",
    "Castelli, Wilhelm": "1",
    "Castrichini, Marcello": "1",
    "Ceretti, Giuseppe": "1",
    "Chaland, Robert": "1",
    "Chiodi, Walter": "1",
    "Chomon, Perino": "1",
    "Cinelli, Silvano": "1",
    "Ciol, Elio": "1",
    "Clarke, Frederick": "1",
    "Clementini, Giuseppe": "1",
    "Clements, Geoffrey": "1",
    "Cleveland, Stephen G.": "1",
    "Cobb, E.S.": "1",
    "Coppola, Bito": "1",
    "Corbara, Antonio": "1",
    "Corsini, Harold": "1",
    "Costi, E.": "1",
    "Crimella, Mario": "1",
    "Cuhel, Emil": "1",
    "Danvers, Alain": "1",
    "Delmas, Charles": "1",
    "Delraux, Albert": "1",
    "Dossi, U.": "1",
    "Doumic, Philippe R.": "1",
    "Ecclesia, Vittorio": "1",
    "Eddy, Don": "1",
    "Effner, Walter": "1",
    "Elfelt, Peter": "1",
    "Faraglia, Cesare": "1",
    "Faxon, Floyd": "1",
    "Fear, Mike": "1",
    "Ferrari, Gianni": "1",
    "Ferrario, Achille": "1",
    "Fiorillo, Edouard": "1",
    "Forero, Diego": "1",
    "Franci, Gino": "1",
    "Frequin, A.": "1",
    "Gasparini, E.": "1",
    "Gerlach, Martin": "1",
    "Giordani, Francesco": "1",
    "Gouder, Alfred Edward": "1",
    "Gourdin, Henri": "1",
    "Grollo, Jos\u00ef\u00bf\u00bd": "1",
    "Guidotti, Fratelli": "1",
    "Guidotti, Guido": "1",
    "Guzzoni, Giulio": "1",
    "Heinz, Noser": "1",
    "Hurel, R.": "1",
    "Judkin, T.R.": "1",
    "Karlsen, Alfred S.": "1",
    "Koti, Andr\u00ef\u00bf\u00bd": "1",
    "Lacoste, Jos\u00ef\u00bf\u00bd": "1",
    "Lazare, R.": "1",
    "Leeser, Paulus": "1",
    "Lembo, Ferdinando": "1",
    "Loobuyck, M.": "1",
    "Luisa, Alberto": "1",
    "Magrelli, Paride": "1",
    "Manias, Jules": "1",
    "Manuel, Henri": "1",
    "Marcucci, Giacomo": "1",
    "Marzullo, Federico": "1",
    "Mates, Robert E./ Katz, Paul": "1",
    "Mattei, Renzo": "1",
    "Mengoli, Giovanni": "1",
    "Mewbourn, Allen": "1",
    "Meyer, Krzystof B.": "1",
    "Michta, Stanislaw": "1",
    "Mille, Daniel": "1",
    "Moulin, Gabriel": "1",
    "Mutter, Johann": "1",
    "Nelson, O. E.": "1",
    "Ogheri, M.": "1",
    "Pais, Francesco": "1",
    "Paltrinieri, Roberto": "1",
    "Paulic, N.": "1",
    "Pessina, Carlo": "1",
    "Peterson, Edward": "1",
    "Petraroli, Eugenio": "1",
    "Petrelli, R.": "1",
    "Polimeni, Paolo": "1",
    "Poplin, Maurice": "1",
    "Poppi, Pietro": "1",
    "Ranzi, Marcello": "1",
    "Reimers, Jan H.": "1",
    "Rigamonti, Eugenio": "1",
    "Rizzi, Lino": "1",
    "Robert, Paul": "1",
    "Rocca, Luigi": "1",
    "Romanowski, Henryk": "1",
    "Rompel, Franz": "1",
    "Rossini, Romana": "1",
    "Routhier, M.": "1",
    "Salvini, Pietro": "1",
    "Scarpa, Pietro": "1",
    "Schiavinotto, Giuseppe": "1",
    "Schmitz, Gregory W.": "1",
    "Scholzig, Otto": "1",
    "Seidner, Zoltan": "1",
    "Senni, Leone": "1",
    "Serra, F.": "1",
    "Smerke, Marjan": "1",
    "Steensma, P.": "1",
    "Stepanek, Rudolf": "1",
    "Stern, Grete": "1",
    "Tabah, Henri": "1",
    "Taddei, Marzio": "1",
    "Thomas, J.W.": "1",
    "Tokarski, George": "1",
    "Toma, Claudio": "1",
    "Trentani, Luigi": "1",
    "Trevisio, E.": "1",
    "Ursini, Federico": "1",
    "Verdoni, Carlo": "1",
    "Vincent, Henry": "1",
    "Waldemar, Jerke": "1",
    "Wills, R.F.": "1",
    "Zafrir, I.": "1",
    "Zerla, Walter": "1"
}

institution = {
    "ICCD: Fototeca Nazionale": "1539",
    "Gabinetto Fotografico della Soprintendenza Speciale per il Patrimonio Storico, Artistico ed Etnoantropologico e per il Polo Museale della citt\u00ef\u00bf\u00bd di Firenze": "929",
    "A. Villani e Figli": "512",
    "A. C. Cooper": "397",
    "Fototeca della Soprintendenza speciale per il patrimonio storico, artistico ed etnoantropologico e per il Polo museale della citt\u00ef\u00bf\u00bd di Napoli": "338",
    "Sotheby's": "284",
    "National Gallery, London": "221",
    "Bildarchiv Foto Marburg": "178",
    "Fiorentini": "167",
    "Christie's": "166",
    "National Gallery of Art, Washington": "147",
    "Arte Fotografica": "129",
    "Prudence Cuming Associates": "117",
    "The Metropolitan Museum of Art": "114",
    "Franz Hanfstaengl": "112",
    "Bayerische Staatsgem\u00ef\u00bf\u00bdldesammlungen Fotothek": "105",
    "Bruckmann Verlag": "99",
    "Compagnia Rotografica": "88",
    "L\u00ef\u00bf\u00bdwy, Josef": "80",
    "Bob Jones University Museum and Gallery Photographic Studios": "78",
    "Fondazione Giorgio Cini": "78",
    "Photo Studios Limited": "78",
    "Archivo M\u00ef\u00bf\u00bds": "75",
    "Fototeca della Soprintendenza per i beni storici, artistici ed etnoantropologici per le province di Milano, Bergamo, Como, Pavia, Sondrio, Lecco, Lodi e Varese": "71",
    "National Gallery of Ireland": "71",
    "Frick Art Reference Library": "70",
    "The Walters Art Museum": "69",
    "Istituto Italiano d'Arti Grafiche": "61",
    "Courtauld Institute of Art": "58",
    "Mus\u00ef\u00bf\u00bde des Beaux-Arts de Dijon": "57",
    "Philadelphia Museum of Art": "54",
    "Bullaty Lomeo Photographers": "53",
    "Accademia Carrara": "52",
    "Fotocommissie Rijksmuseum Amsterdam": "51",
    "Tilli": "47",
    "Gabinetto Fotografico della Soprintendenza per i beni storici, artistici ed etnoantropologici delle Marche": "46",
    "R. B. Fleming and Co.": "46",
    "Foto Reali": "42",
    "Gasparini": "41",
    "Mus\u00ef\u00bf\u00bde des Beaux-Arts de Chamb\u00ef\u00bf\u00bdry": "41",
    "Harvard University Art Museums, Fogg Art Museum": "40",
    "Gabinetto Fotografico della Soprintendenza per i beni storici, artistici ed etnoantropologici dell'Umbria": "39",
    "Museum of Fine Arts, Boston": "37",
    "Statens Museum for Kunst": "37",
    "Fotofast": "36",
    "Fototeka Narodne Galerije, Ljubljana": "35",
    "Samuel H. Kress Collection": "35",
    "Detroit Institute of Arts": "34",
    "Gem\u00ef\u00bf\u00bdldegalerie, Staatliche Museen zu Berlin": "34",
    "John and Mable Ringling Museum of Art": "34",
    "Giraudon": "33",
    "Victoria and Albert Museum": "33",
    "A.F.I. - Agenzia Fotografica Industriale": "31",
    "Brunel": "29",
    "Fototeca Unione": "29",
    "Archivio fotografico della Soprintendenza per i beni storici, artistici ed etnoantropologici della Sardegna": "27",
    "Nationalmuseum Stockholm": "27",
    "Caldarazzo": "26",
    "Mus\u00ef\u00bf\u00bde Magnin de Dijon": "26",
    "F. & O. Brockmann": "24",
    "Archivio fotografico della Soprintendenza per i beni storici, artistici ed etnoantropologici per le province di Bologna, Ferrara, Forl\u00ef\u00bf\u00bd-Cesena, Ravenna e Rimini e Pinacoteca Nazionale di Bologna": "23",
    "Archivio fotografico della Soprintendenza per i Beni architettonici e il paesaggio e per il patrimonio storico, artistico e etnoantropologico per le province di Lucca e Massa Carrara": "20",
    "Cleveland Museum of Art": "20",
    "Archivio fotografico dei Musei Vaticani": "19",
    "Mus\u00ef\u00bf\u00bde d'Art et d'Histoire Gen\u00ef\u00bf\u00bdve": "19",
    "Agenzia Fotografica Internazionale": "18",
    "Archivio Fotografico della Soprintendenza Speciale per i beni storici, artistici ed etnoantropologico per il Polo Museale della citt\u00ef\u00bf\u00bd di Venezia e dei Comuni della Gronda Lagunare": "18",
    "Ashmolean Museum of Art and Archeology": "18",
    "Braun": "18",
    "Kunsthistorisches Museum Wien": "18",
    "Musei Civici agli Eremitani di Padova, Gabinetto fotografico": "18",
    "Staatsgalerie Stuttgart": "18",
    "Yale University Art Gallery": "18",
    "Henry Dixon and Son": "17",
    "Jacquier": "17",
    "Archivio e Laboratorio fotografico della Soprintendenza per i beni storici, artistici ed etnoantropologici per le province di Verona, Rovigo e Vicenza": "16",
    "Centre des monuments nationaux, agence photographique": "16",
    "Kunsthistorisches Institut Florenz": "16",
    "Museo Regionale di Messina": "16",
    "Schwitter": "16",
    "Agence photographique de la R\u00ef\u00bf\u00bdunion des Mus\u00ef\u00bf\u00bdes Nationaux": "15",
    "Los Angeles County Museum of Art": "15",
    "Staatliche Kunsthalle Karlsruhe": "15",
    "The Art Institute of Chicago": "15",
    "B\u00ef\u00bf\u00bdhm, Osvaldo": "14",
    "Fototeca del Museo Poldi Pezzoli": "14",
    "Glasgow Art Gallery and Museum": "14",
    "Museo dell'Ermitage (Gosudarstvennyj Eremitage)": "14",
    "Worcester Art Museum": "14",
    "Archivio fotografico Musei Civici Veneziani": "13",
    "Archivio fotografico della Soprintendenza speciale per il patrimonio storico, artistico ed etnoantropologico e per il Polo museale della citt\u00ef\u00bf\u00bd di Roma": "13",
    "Regione Liguria, Servizio Beni e attivit\u00ef\u00bf\u00bd culturali": "13",
    "Royal Academy of Arts": "13",
    "Annan": "12",
    "Borchi": "12",
    "Frick Collection": "12",
    "Negri": "12",
    "Van Diemen-Lilienfeld Galleries": "12",
    "Archivio Fotografico Luce": "11",
    "Brooklyn Museum of Art": "11",
    "Istituto Centrale di Patologia del Libro: Fototeca": "11",
    "Istituto Superiore per la Conservazione ed il Restauro: Archivio fotografico": "11",
    "National Gallery of Canada": "11",
    "Rheinisches Bildarchiv": "11",
    "Ufficio fotografico della Soprintendenza per i beni storici, artistici ed etnoantropologici per le province di Modena e Reggio Emilia": "11",
    "Cross Photos": "10",
    "Giacomelli": "10",
    "Gibbs": "10",
    "Lucenti Foto Ottica": "10",
    "San Diego Museum of Art": "10",
    "Schaeffer Galleries": "10",
    "The Minneapolis Institute of Arts": "10",
    "C.N.B.": "9",
    "Editorial Photo": "9",
    "Fototeca della Soprintendenza per beni architettonici e paesaggistici, storici, artistici ed etnoantropologici per le province di Pisa e Livorno": "9",
    "Fototecnica Bolognese": "9",
    "Hauser y Menet": "9",
    "Interfoto": "9",
    "Musei Civici di Pesaro": "9",
    "Muzeum Narodowe w Warszawie": "9",
    "The Baltimore Museum of Art": "9",
    "Video - Roma": "9",
    "Bardazzi Fotografia": "8",
    "Ehrich Galleries": "8",
    "Giovara": "8",
    "Sotheby Parke-Bernet": "8",
    "Sz\u00ef\u00bf\u00bdpm\u00ef\u00bf\u00bdv\u00ef\u00bf\u00bdszeti M\u00ef\u00bf\u00bdzeum Budapest": "8",
    "The Fine Arts Museums of San Francisco": "8",
    "The Snite Museum of Art": "8",
    "Vaering": "8",
    "Vajenti": "8",
    "Walker Art Center": "8",
    "Walker Art Gallery": "8",
    "Allen Memorial Art Museum": "7",
    "Alterocca": "7",
    "Archivio fotografico della Soprintendenza per i beni storici, artistici ed etnoantropologici della Liguria": "7",
    "Burris": "7",
    "Cuming Wright-Watson Associates": "7",
    "D'Alessandri, Fratelli": "7",
    "Isabella Stewart Gardner Museum": "7",
    "Istituto Nazionale per la Grafica": "7",
    "Lafayette Photography": "7",
    "Neurdein": "7",
    "Silberman Galleries": "7",
    "Vernacci Ruiz, Joaquin": "7",
    "Browns": "6",
    "Foto Wells": "6",
    "IRPA-KIK Institut royal du Patrimoine artistique-Koninklijk Instituut voor het Kunstpatrimonium": "6",
    "Ideal Foto Cine di Colacioppo": "6",
    "Institut Mainini": "6",
    "Lombardi": "6",
    "Museum of Fine Arts Saint Petersburg": "6",
    "Photographische Gesellschaft Berlin": "6",
    "Princeton University Art Museum": "6",
    "Studio Fotografico AS": "6",
    "Studio fotografico Orlandini": "6",
    "Bern\u00ef\u00bf\u00bds, Marouteau et Compagnie": "5",
    "Da Re, Umberto": "5",
    "Dall'Armi, Gian Carlo": "5",
    "Deutsche Fotothek": "5",
    "Foto-Studio H. Humm": "5",
    "Fototeca della Soprintendenza per i beni storici, artistici ed etnoantropologici del Piemonte": "5",
    "French and Co.": "5",
    "Laboratorio Fotografico Corso": "5",
    "Liechtenstein Museum, Wien": "5",
    "North Carolina Museum of Art": "5",
    "Solar Aircraft Company": "5",
    "Staatliche Kunstsammlungen Dresden": "5",
    "Strossmayerova Galerija starih majstora": "5",
    "Taylor and Dull": "5",
    "The Wallace Collection": "5",
    "Archivio Fotografico Scala": "4",
    "Archivio fotografico della Soprintendenza per i beni storici, artistici ed etnoantropologici per le province di Parma e Piacenza": "4",
    "Carbonora": "4",
    "Charles Smith Studio": "4",
    "Danesi": "4",
    "Fototecnica Fortunati": "4",
    "Joslyn Art Museum": "4",
    "La Fototecnica": "4",
    "Martin-von-Wagner-Museum der Universit\u00ef\u00bf\u00bdt W\u00ef\u00bf\u00bdrzburg": "4",
    "Moreno": "4",
    "Nelson-Atkins Museum of Art": "4",
    "Nieders\u00ef\u00bf\u00bdchsische Landesgalerie": "4",
    "Piaget": "4",
    "Randazzo": "4",
    "Studio d'arte Palma": "4",
    "The Clowes Fund, Fine Arts Department": "4",
    "Universit\u00ef\u00bf\u00bd di Pisa. Dipartimento di Storia delle Arti": "4",
    "Wadsworth Atheneum Museum of Art": "4",
    "Archivio fotografico della Soprintendenza per i Beni Architettonici e Paesaggistici per le province di Roma, Frosinone, Latina, Rieti e Viterbo": "3",
    "Barber Institute of Fine Arts, University of Birmingham": "3",
    "Bonhams": "3",
    "Bottega d'Arte": "3",
    "Burloni": "3",
    "Carnegie Museum of Art": "3",
    "Centre de recherche et de restauration des mus\u00ef\u00bf\u00bdes de France": "3",
    "Cincinnati Art Museum": "3",
    "D'Amico, Fratelli": "3",
    "De Antonis, Riccardo": "3",
    "De Vogelaere, A.": "3",
    "De Wan Studios": "3",
    "Elsner & Son": "3",
    "Foto Dalmazio": "3",
    "Foto Ferruzzi": "3",
    "Foto Ottica Ciocci": "3",
    "Fotohaus am Dom": "3",
    "Galleria Bellini": "3",
    "Giorgio Laurati & C.": "3",
    "Graves Art Gallery": "3",
    "Gudiol": "3",
    "Haeseler Photographic Studios": "3",
    "Indianapolis Museum of Art": "3",
    "Lotze": "3",
    "P. E. Chauffourier": "3",
    "Phoenix Art Museum": "3",
    "Saint Louis Art Museum": "3",
    "Smithsonian Institution, National Collection of Fine Arts": "3",
    "Solaria Fotografia": "3",
    "Studio Art Photos": "3",
    "Studio Fotografico Perotti": "3",
    "Studio fotografico Bandieri": "3",
    "Vaul\u00ef\u00bf\u00bd, Y.": "3",
    "Wildenstein": "3",
    "Zambruno": "3",
    "Archivio Fotografico dell'Universit\u00ef\u00bf\u00bd di Bologna": "2",
    "Associated Commercial Photographers": "2",
    "Atelier 53": "2",
    "Bozzato": "2",
    "Busch-Hauck, Gabriele": "2",
    "Coulbourn Brown, W.": "2",
    "Edizioni d'Arte Pandimiglio": "2",
    "Electa": "2",
    "Elvehjem Museum of Art, University of Wisconsin": "2",
    "Foto Barsotti": "2",
    "Foto Boero": "2",
    "Foto Gioberti": "2",
    "Foto Locchi": "2",
    "Foto Moderna": "2",
    "Foto Paoletti di Mario Zacchetti": "2",
    "Foto Parlatini": "2",
    "Foto Pugnaghi": "2",
    "Foto Studio Color": "2",
    "Fotografia A. Premi": "2",
    "Fotografia Artistica Industriale. Rinaldo Schreiber": "2",
    "Fotottica Aldo": "2",
    "Frankenstein": "2",
    "Galleria Gasparrini": "2",
    "Gem\u00ef\u00bf\u00bdldegalerie der Akademie der bildenden K\u00ef\u00bf\u00bdnste": "2",
    "Giroud": "2",
    "Guggenb\u00ef\u00bf\u00bdhl, Peter": "2",
    "Hutrel": "2",
    "Immagine fotografica": "2",
    "Kimbell Art Museum": "2",
    "Kleinberger Galleries": "2",
    "Lazzeri": "2",
    "Lupatelli Roncalli, Saverio": "2",
    "Magyar Film Iroda": "2",
    "Museo Nacional de Bellas Artes, Taller Fotogr\u00ef\u00bf\u00bdfico": "2",
    "Museo Nacional del Prado. Laboratorio fotografico": "2",
    "New York Historical Society": "2",
    "N\u00ef\u00bf\u00bdrodn\u00ef\u00bf\u00bd galerie v Praze": "2",
    "O' Sughrue, Claude": "2",
    "Olivi Fotocolor": "2",
    "Olsson J.F. & Co.": "2",
    "Pax et Bonum": "2",
    "Publifoto": "2",
    "Recalcati": "2",
    "Reiffenstein": "2",
    "Rijksmuseum Kr\u00ef\u00bf\u00bdller-M\u00ef\u00bf\u00bdller": "2",
    "Royal Collection": "2",
    "Sisti": "2",
    "Soprintendenza Beni Culturali ed Ambientali Palermo": "2",
    "Staatliche Kunstsammlungen Kassel": "2",
    "Stadelschen Kunstinstituts Frankfurt": "2",
    "Stearn & Sons": "2",
    "Studio Fotografico Da Re": "2",
    "Studio Fotografico Moderno": "2",
    "Studio d'Arte Fotografica Mastellone": "2",
    "Tarbox Beals, Jessie": "2",
    "Tecnifoto": "2",
    "The College Studios": "2",
    "The Corcoran Gallery of Art": "2",
    "The Montreal Museum of Fine Arts": "2",
    "The Toledo Museum of Art": "2",
    "Ufficio Fotoriproduzioni. Biblioteca Ambrosiana": "2",
    "Ulster Museum": "2",
    "Virginia Museum of Fine Arts": "2",
    "Wehrli": "2",
    "Accademia dei Concordi": "1",
    "Allegri Ugo Fotografia": "1",
    "Alt-Lee": "1",
    "Archivio Fotografico della Fondazione Torino Musei": "1",
    "Archivio e Laboratorio fotografico della Soprintendenza per i beni artistici, storici ed etnoantropologici per le province di Venezia, Belluno, Padova e Treviso": "1",
    "Archivio fotografico della Soprintendenza per i beni storici, artistici ed etnoantropologici per le province di Brescia, Cremona e Mantova": "1",
    "Arslan E.": "1",
    "Atelier Arzt": "1",
    "Atelier Dager": "1",
    "Atelier Municipal de Reprographie": "1",
    "B.P.M.": "1",
    "Ball State University": "1",
    "Bearne's": "1",
    "Bellavigna": "1",
    "Benedict": "1",
    "Bertoni": "1",
    "Bilden Illustrationsfoto": "1",
    "Blauel/Gnamm - Artothek": "1",
    "Bolognesi - Orsini": "1",
    "Borel-Boissonnas, Gad": "1",
    "Bratic": "1",
    "British Museum": "1",
    "Br\u00ef\u00bf\u00bdnel": "1",
    "Burton": "1",
    "Busi": "1",
    "CTK": "1",
    "Cantera": "1",
    "Caprioli": "1",
    "Caratelli": "1",
    "Cartwright Hall Art Gallery": "1",
    "Centro Internazione di Documentazione per le Arti": "1",
    "Chaucer Fine Arts": "1",
    "Chierici": "1",
    "Cinecolorfoto": "1",
    "Cinefototecnica La Greca": "1",
    "City Art Gallery Bristol": "1",
    "City Art Gallery Manchester": "1",
    "Ciurnelli": "1",
    "Civico Archivio Fotografico del Comune di Milano": "1",
    "Colin Jeffrey Associates": "1",
    "Collezioni Reali, Stoccolma": "1",
    "Colten": "1",
    "Colten & Siegler": "1",
    "Comisi\u00ef\u00bf\u00bdn Nacional de Museos y Lugares Hist\u00ef\u00bf\u00bdricos": "1",
    "Cooper and Humphreys": "1",
    "Dalla Casa": "1",
    "Dayton Art Institute": "1",
    "De Antonis, Pasquale": "1",
    "De Federicis, Francesco": "1",
    "Felici": "1",
    "Fine Art Engravers Ltd.": "1",
    "Foto Atelier Bijl": "1",
    "Foto Bleynat": "1",
    "Foto Conca": "1",
    "Foto Cortopassi": "1",
    "Foto Cresta": "1",
    "Foto Laboratorio Vito e Damiano": "1",
    "Foto Massa": "1",
    "Foto Visconti": "1",
    "Fotoattualit\u00ef\u00bf\u00bd di Attilio Costantini": "1",
    "Fotografia Rossi": "1",
    "Fotostampa Ficarelli": "1",
    "Fotostudio Fazioli": "1",
    "Fotostudio Max": "1",
    "Fototeca dei Civici Musei e Gallerie di Storia dell'Arte di Udine": "1",
    "Fototeca dei Musei Civici d'Arte e Storia di Brescia": "1",
    "Fototeca della Soprintendenza per i Beni Architettonici e per il Paesaggio, per il Patrimonio Storico, Artistico ed Etnoantropologico della Provincia di Arezzo": "1",
    "Fototecnica Brasilia": "1",
    "Fox Photos": "1",
    "Froment": "1",
    "Galerie Heinemann": "1",
    "Galerie Trotti": "1",
    "Gallerini": "1",
    "Ghilain-Attenelle": "1",
    "Giancarlo Baroni Tableaux": "1",
    "Giancolombo": "1",
    "Giandean": "1",
    "Giovetti": "1",
    "Giovetti Fotografia & Comunicazioni Visive": "1",
    "Grace Gallery": "1",
    "Green Studio Ltd.": "1",
    "Griffith W. - Photographers Associated": "1",
    "H.J. Chapman & Co.": "1",
    "Harari and Johns": "1",
    "Hazlitt Gallery": "1",
    "Helga Photo Studio": "1",
    "Henry E. Huntington Library and Art Gallery": "1",
    "Honolulu Academy of Arts": "1",
    "Hood Museum of Art, Dartmouth College": "1",
    "H\u00ef\u00bf\u00bdch, Franz": "1",
    "H\u00ef\u00bf\u00bdflinger, August": "1",
    "International Foundation for Art Research, Inc. (IFAR)": "1",
    "Iris and B. Gerald Cantor Center for Visual Arts at Stanford University": "1",
    "Istituto Nazionale di Archeologia e Storia dell'Arte. Fototeca": "1",
    "J. Paul Getty Museum": "1",
    "Jonals og Co.": "1",
    "Jones & Morris": "1",
    "Kantonspolizei": "1",
    "Kestner Museum": "1",
    "Kleinhempel": "1",
    "Knorr & Hirth": "1",
    "Kr\u00ef\u00bf\u00bdner, Wilhelm": "1",
    "L.F.P.": "1",
    "L.I.F.E. Mazzitelli Vincenzo": "1",
    "Leasarte": "1",
    "Light Fotofilm": "1",
    "Lori": "1",
    "Lux et Umbra": "1",
    "Mauritshuis": "1",
    "Mayer": "1",
    "Memorial Hall": "1",
    "Millar and Harris": "1",
    "Minarini": "1",
    "Museo Civico G. Ferrari": "1",
    "Museo Civico di Vicenza": "1",
    "Museo Nazionale di Castel Sant'Angelo: Archivio Fotografico": "1",
    "Museum Schloss Wilhelmsh\u00ef\u00bf\u00bdhe, Gem\u00ef\u00bf\u00bdldegalerie Alte Meister": "1",
    "Mus\u00ef\u00bf\u00bde National des Beaux-Arts d'Alger": "1",
    "Mus\u00ef\u00bf\u00bde de la Chartreuse de Douai": "1",
    "Mus\u00ef\u00bf\u00bde des Arts D\u00ef\u00bf\u00bdcoratifs": "1",
    "Mus\u00ef\u00bf\u00bde des Beaux Arts de Nantes": "1",
    "Mus\u00ef\u00bf\u00bde des Beaux-Arts de Marseille": "1",
    "Mus\u00ef\u00bf\u00bde des Beaux-Arts de Tours": "1",
    "Muzeum Narodowe w Poznaniu": "1",
    "Nannini": "1",
    "National Galleries of Scotland": "1",
    "National Gallery of Victoria": "1",
    "Neocolor s.r.l.": "1",
    "Newman Fury": "1",
    "News Blitz Photoreportages": "1",
    "Nicola": "1",
    "Norton Museum of Art": "1",
    "O'Reilly, Michael": "1",
    "Odon Wagner Gallery": "1",
    "Opificio delle Pietre Dure, Archivio restauri": "1",
    "Pach Brothers": "1",
    "Parke-Bernet": "1",
    "Perena": "1",
    "Philbrook Museum of Art": "1",
    "Photo Boissonnas": "1",
    "Photo Etienne": "1",
    "Photo L'Epi-Devolder": "1",
    "Photo-Capitole": "1",
    "Photo-Haas": "1",
    "Photochromes Z\u00ef\u00bf\u00bdrich": "1",
    "Photopress": "1",
    "Photopress Italiana": "1",
    "Photos": "1",
    "Photos Cauvin": "1",
    "Pinacoteca Civica": "1",
    "Pinacoteca Civica Tosio-Martinengo": "1",
    "Portugal": "1",
    "Por\u00ef\u00bf\u00bde, Monique": "1",
    "Quadreria Arcivescovile": "1",
    "Rheinisches Landesmuseum Bonn": "1",
    "Ritter-Jeppesen Studios": "1",
    "S.F.E.R.": "1",
    "SAP": "1",
    "Salmon Printers & Publishers": "1",
    "Sansoni e Valentini": "1",
    "Schepis": "1",
    "Schweizerisches Institut f\u00ef\u00bf\u00bdr Kunstwissenschaft": "1",
    "Seyve Cristofoli, Martine": "1",
    "Silvestre": "1",
    "Spencer Museum of Art, University of Kansas": "1",
    "Stabilimento fotografico A. Tancredi": "1",
    "Steiner & Schroff": "1",
    "Sterling and Francine Clark Art Institute": "1",
    "Studio Calzolari": "1",
    "Studio CiGi 1": "1",
    "Studio Guy": "1",
    "Studio Vaiani": "1",
    "St\u00ef\u00bf\u00bddelsches Kunstinstitut und St\u00ef\u00bf\u00bddtische Galerie Frankfurt": "1",
    "St\u00ef\u00bf\u00bddtische Kunstsammlungen Augsburg": "1",
    "The Fitzwilliam Museum": "1",
    "The Hyde Collection": "1",
    "The Lyman Allyn Museum": "1",
    "The Museum of Fine Arts": "1",
    "The Sensor Studios": "1",
    "Tiozzo": "1",
    "Todd-White": "1",
    "Trapani": "1",
    "Umberto Allemandi & C.": "1",
    "Unione Tipografica Cooperativa": "1",
    "University of Arizona Art Gallery": "1",
    "Universit\u00ef\u00bf\u00bd di Catania: Istituto di Storia dell'Arte": "1",
    "Vanadio": "1",
    "Verde O., Jos\u00ef\u00bf\u00bd": "1",
    "Visual Aids Department University of Melbourne": "1",
    "Wright-Watson, Rodney": "1",
    "York City Art Gallery": "1"
}

def count_contributions(dict):
    count = 0 
    for key, value in dict.items():
        count = count + int(value)
    return count


print("The total number of contributions from institutions is: " + str(count_contributions(institution)) + ", with " + str(len(institution)) + " institutions contributing.")
print("The total number of contributions from individual photographers is: " + str(count_contributions(people)) + ", with " + str(len(people)) + " contributing.")